name: Rust

on:
  release:
    types: [prereleased]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Test
      run: ls target/release/
    - name: Upload binaries to release for windows
      if: matrix.platform == 'windows-latest'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/p2p_port_mapper.exe
        asset_name: p2p-port-mapper-${{ matrix.platform }}.exe
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - name: Upload binaries to release for linux
      if: matrix.platform != 'windows-latest'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/p2p_port_mapper
        asset_name: p2p-port-mapper-${{ matrix.platform }}
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
